import { expect, test } from '@playwright/test'

test('Saved explains how to keep the first plan without interrupting planning', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Portland controlled alpha').first()).toBeVisible()
  await page.getByRole('button', { name: 'Build my Portland plan' }).click()
  await expect(page.getByRole('heading', { name: 'Where should the date happen?' })).toBeVisible()

  await page.getByRole('button', { name: 'Saved (0)' }).click()
  await expect(page.getByRole('dialog', { name: 'Saved plans' })).toBeVisible()
  await expect(page.getByText('Choose Save plan from a ranked option or its itinerary.')).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await expect(page.getByRole('heading', { name: 'Where should the date happen?' })).toBeVisible()
})

test('Step 2 exposes exactly one selected date preset', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Build my Portland plan' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('heading', { name: 'When and how flexible?' })).toBeVisible()

  const presets = page.getByRole('group', { name: 'Date presets' }).getByRole('button')
  await expect(presets).toHaveCount(3)
  await expect(page.locator('[role="group"][aria-label="Date presets"] button[aria-pressed="true"]')).toHaveCount(1)
})

test('personal planning starts clean and corrects street-like input before advancing', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Build my Portland plan' }).click()
  await expect(page.getByText('Demo profile')).toHaveCount(0)

  await page.getByPlaceholder('City or neighborhood').fill('1234 SE Privacy Leak St, Portland, OR')
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('alert')).toContainText('We replaced the street address with Portland, OR.')
  await expect(page.getByRole('heading', { name: 'Where should the date happen?' })).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('heading', { name: 'When and how flexible?' })).toBeVisible()
})

test('example route stays labeled and its safety share matches the visible itinerary', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Preview a clearly labeled demo' }).click()
  await expect(page.getByText('Demo profile')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pick the plan before we build the full itinerary.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Real restaurant and café ideas for this brief.' })).toBeVisible()
  await expect(page.locator('.curated-venue-card')).toHaveCount(4)
  await expect(page.locator('.curated-venue-card').first()).toContainText('Verify directly before leaving.')
  await expect(page.locator('.curated-venue-card').first().locator('.venue-kind')).toContainText(/current guide|multi-list consensus|founder seed/)
  await expect(page.locator('.curated-venue-card').first().locator('.venue-kind')).toContainText('restaurant')
  const chosenVenueCard = page.locator('.curated-venue-card').nth(1)
  const chosenVenueName = await chosenVenueCard.locator('strong').first().innerText()
  await chosenVenueCard.getByRole('button', { name: 'Use this venue' }).click()
  await expect(chosenVenueCard.getByRole('button', { name: 'Selected venue' })).toBeVisible()
  await page.getByRole('button', { name: 'Save plan' }).click()
  await expect(page.getByRole('button', { name: 'Saved (1)' })).toBeVisible()
  await page.locator('.curated-venue-card').nth(2).getByRole('button', { name: 'Use this venue' }).click()
  await page.getByRole('button', { name: 'Saved (1)' }).click()
  const savedDialog = page.getByRole('dialog', { name: 'Saved plans' })
  await expect(savedDialog).toContainText(`Venue: ${chosenVenueName}`)
  await savedDialog.getByRole('button', { name: 'Open' }).click()
  await expect(page.locator('.itinerary')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Update saved plan' })).toBeVisible()
  await expect(page.getByLabel('Plan summary')).toContainText(chosenVenueName)
  await expect(page.getByLabel('Curated venue flex option')).toContainText('Same-area backup')
  await expect(page.getByLabel('Curated venue flex option')).toContainText('not booked')
  await expect(page.getByLabel('Curated venue flex option')).toContainText(chosenVenueName)
  await expect.poll(() => page.locator('.bottom-nav').evaluate((element) => getComputedStyle(element).position)).toBe('static')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)

  await page.getByRole('button', { name: 'Safety share' }).click()
  const safetyText = page.getByRole('dialog', { name: 'Safety share' }).getByRole('textbox')
  const safetyValue = await safetyText.inputValue()
  const safetyStops = safetyValue.split('Public stops:')[1]
  expect(safetyValue).toContain('Date:')
  expect(safetyStops.match(/Laurelhurst Park/g)).toHaveLength(2)
  expect(safetyStops.indexOf('Laurelhurst Market')).toBeGreaterThan(safetyStops.lastIndexOf('Laurelhurst Park'))
  expect(safetyStops.indexOf('Rimsky-Korsakoffee House')).toBeGreaterThan(safetyStops.indexOf('Laurelhurst Market'))
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: 'Adjust' }).click()
  await expect(page.getByRole('heading', { name: 'Preview an adjusted plan, then keep it or choose another change.' })).toBeVisible()
  await page.getByRole('button', { name: /Make cheaper/ }).click()
  await page.getByRole('button', { name: 'Keep adjusted plan' }).click()
  await expect(page.locator('.itinerary')).toBeVisible()

  await page.getByRole('button', { name: 'Safety share' }).click()
  const adjustedSafetyValue = await page.getByRole('dialog', { name: 'Safety share' }).getByRole('textbox').inputValue()
  const adjustedSafetyStops = adjustedSafetyValue.split('Public stops:')[1]
  expect(adjustedSafetyStops.indexOf('Portland Art Museum')).toBeGreaterThan(adjustedSafetyStops.indexOf('Barista Pearl District'))
  expect(adjustedSafetyStops.indexOf('Pix Patisserie')).toBeGreaterThan(adjustedSafetyStops.indexOf('Portland Art Museum'))
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: 'Alerts' }).click()
  await page.getByRole('button', { name: 'Edit demo reminders' }).click()
  await expect(page.getByRole('dialog', { name: 'Demo reminder setup' })).toBeVisible()
  await expect(page.getByText('These are copyable demo reminders only.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Demo reminder setup' })).toBeHidden()
})
